---
- name: Generate systemd.link files
  loop: "{{ interfaces }}"
  template:
    src: 50-interface.link.j2
    dest: "/etc/systemd/network/50-{{ item['name'] }}.link"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate systemd.netdev files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
  - 60-skynet.netdev
  - 60-novotelecom.netdev
  - 60-mts.netdev
  - 60-home.netdev
  - 60-isp1.netdev
  - 60-isp2.netdev
  - 60-management.netdev

- name: Generate systemd.network files for links
  loop: "{{ interfaces }}"
  template:
    src: 70-interface.network.j2
    dest: "/etc/systemd/network/65-{{ item['name'] }}.network"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate systemd.network files for VLANs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
  - 70-management.network
  - 70-skynet.network
  - 70-novotelecom.network
  - 70-mts.network
  - 70-home.network
  - 70-isp1.network
  - 70-isp2.network

- name: Enable, start/restart systemd-networkd unit
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: yes
    enabled: yes
