---
- name: Clear systemd-networkd configuration files
  file:
    path: '/etc/systemd/network/{{ item }}'
    state: absent
  with_fileglob:
     - /etc/systemd/network/*

- name: Copy systemd-networkd common files
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
  - 55-home.netdev
  - 55-skynet.netdev
  - 60-management.netdev
  - 70-home.network

- name: Generate systemd-networkd link files
  loop: "{{ interfaces }}"
  template:
    src: 50-ifname.link.j2
    dest: "/etc/systemd/network/50-{{ item['name'] }}.link"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate systemd-networkd link network files
  loop: "{{ interfaces }}"
  template:
    src: 65-ifname.network.j2
    dest: "/etc/systemd/network/65-{{ item['name'] }}.network"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate systemd-networkd other network files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
  - 65-management.network
  - 70-skynet.network

- name: Enable/restart systemd-networkd unit
  systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: yes
    enabled: yes
