---
- name: Remove packages
  apt:
    name: "{{ item }}"
    state: absent
    autoclean: yes
    autoremove: yes
    purge: yes
    update_cache: yes
  loop:
  - ubuntu-server
  - ubuntu-standard
  - unattended-upgrades
  - ufw
  - secureboot-db
  - sbsigntool
  - cloud-init
  - uuid-runtime
  - netplan.io

- name: Upgrade packages
  apt:
    upgrade: yes
    autoclean: yes
    autoremove: yes
    update_cache: yes

- name: Install/update packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
  - systemd
  - nftables
  - keepalived
  - dnsmasq
  - stubby

- name: Disable systemd units
  systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: yes
    enabled: no
  loop:
  - ondemand.service
  - snap.lxd.daemon.unix.socket
  - systemd-resolved
