---
- name: Remove packages
  apt:
    name: "{{ item }}"
    state: absent
    autoclean: yes
    autoremove: yes
    purge: yes
    update_cache: yes
  loop:
  - ubuntu-server
  - ubuntu-standard
  - unattended-upgrades
  - apparmor
  - ufw
  - secureboot-db
  - sbsigntool
  - cloud-init
  - uuid-runtime
  - netplan.io

- name: Remove paths
  file:
    state: absent
    path: "{{ item }}"
  loop:
  - /usr/share/netplan/netplan/cli/commands
  - /etc/netplan
  - /etc/cloud/cloud.cfg.d
  - /var/log/unattended-upgrades
  - /var/lib/update-manager

- name: Upgrade packages
  apt:
    upgrade: yes
    autoclean: yes
    autoremove: yes
    update_cache: yes

- name: Disable systemd units
  systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: yes
    enabled: no
  loop:
  - ondemand.service
  - snap.lxd.daemon.unix.socket

- name: Add repositories keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
  - https://www.apache.org/dist/cassandra/KEYS

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
  - deb http://www.apache.org/dist/cassandra/debian 39x main

- name: Install/update packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
  - systemd
  - nftables
  - cassandra
  - keepalived
  - kea-dhcp4-server