---
- name: Install skynet cluster
  hosts: skynet
  become: yes
  roles:
  - ubuntu-server-minimizer
  - systemd-networkd
  - systemd-resolved
  - disable-swap
  - keepalived
  - cassandra
  - reboot
