---
- name: Install skynet cluster
  hosts: skynet
  become: yes
  roles:
  #- disable-swap
  #- ubuntu-server
  #- linux_modules
  #- sysctl
  #- systemd-networkd
  #- reboot
  #- nftables
  - keepalived
  #- stubby
  #- dnsmasq
  #- resolve
