---
- name: Install skynet cluster
  hosts: skynet
  become: yes
  roles:
  #- ubuntu-server
  #- linux-modules
  #- sysctl
  #- systemd-networkd
  #- reboot
  #- nftables
  #- keepalived
  #- systemd-resolved
  #- dnsmasq
