---
- name: Install skynet cluster
  hosts: skynet
  become: yes
  roles:
  #- ubuntu-server
  - systemd-networkd
  - stubby
  - keepalived
  - nftables
  #- etcd
  - isc-dhcp-server
  - sysctl
  - disable-swap
  #- reboot
