---
keepalived:
  password: "{{ lookup('password', '/tmp/keepalived.pass chars=ascii_letters') }}"
  id: 100
  name: skynet_vip
  notify:
    isp1:
      mac: 60:a4:4c:6d:c6:00
      address: 5.130.78.89
      network: "24"
      gateway: 5.130.78.1
    isp2:
      mac: c8:3a:35:d8:e9:53
      address: ""
      network: "24"
      gateway: ""
    home:
      mac: fe:12:34:56:78:90
      address: 192.168.123.1
      network: "24"
    skynet:
      address: 192.168.128.1
      network: "17"
