---
networking:

  arp_mon_list:
  - 192.168.111.1
  - 192.168.111.2

  vlan_ids:
    isp1: 121
    isp2: 122
    home: 123
    skynet: 128

  vrrp:
    id: 1
    device: skynet
    password: skynet
    priority: "{{ vrrp_priority }}"
    vip:
      management:
        address: 192.168.111.10
        network: 32
      skynet:
        address: 192.168.128.1
        network: 32
      home:
        address: 192.168.123.1
        network: 24
      isp1:
        address: 5.130.78.89
        network: 24
        gateway: 5.130.78.1
        fwmark: 121
        default: true
      isp2:
        address: 109.174.122.53
        network: 26
        gateway: 109.174.122.1
        fwmark: 122

  ip: "{{ ip }}"

  interfaces: "{{ interfaces }}"

  ipam: "{{ ipam }}"
