---
shared_addresses:
  arp_mon: 192.168.111.1 192.168.111.2
  skynet_router:
    address: 192.168.128.1
    network: "17"
  home_router:
    address: 192.168.123.1
    network: "24"
  isp1:
    address: 5.130.78.89
    network: "24"
    gateway: 5.130.78.1
  isp2:
    address: ""
    network: "24"
    gateway: ""
