---
unbound:
  upstreams:
  - name: one.one.one.one
    address: 1.0.0.1
    port: 853
  - name: one.one.one.one
    address: 1.1.1.1
    port: 853
  - name: dns.google
    address: 8.8.4.4
    port: 853
  - name: dns.google
    address: 8.8.8.8
    port: 853
  - name: dns.quad9.net
    address: 9.9.9.9
    port: 853
  - name: dns.quad9.net
    address: 149.112.112.112
    port: 853
  allow_networks:
  - 10.0.0.0/8
  - 192.168.0.0/16
  interfaces:
  - "{{ networking.vrrp.vip.skynet.address }}"
  - "{{ networking.vrrp.vip.home.address }}"
