---
vrrp:
  id: 1
  device: skynet
  password: skynet
  priority: "{{ vrrp_priority }}"
  vip:
    skynet:
      address: 192.168.128.1
      network: 32
    home:
      address: 192.168.123.1
      network: 24
    isp1:
      address: 5.130.78.89
      network: 24
      gateway: 5.130.78.1
      fwmark: 121
      default: true
    isp2:
      address: 109.174.122.53
      network: 26
      gateway: 109.174.122.1
      fwmark: 122
