---
- name: Disable cache for systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?Cache='
    line: "Cache=no"
    state: present

- name: Create a symbolic link for resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    force: yes

- name: Enable/restart systemd-resolved unit
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes
    enabled: yes
