---
- name: Enable cache for systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?Cache='
    line: "Cache=yes"
    state: present

- name: Enable DNSOverTLS mode for systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSOverTLS='
    line: "DNSOverTLS=yes"
    state: present

- name: Use Cloudflare DNS for systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: "DNS=1.1.1.1 1.0.0.1"
    state: present

- name: Use Google FallbackDNS for systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?FallbackDNS='
    line: "FallbackDNS=8.8.8.8 8.8.4.4"
    state: present

- name: Enable DNSStubListener mode for systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener='
    line: "DNSStubListener=yes"
    state: present

- name: Create a symbolic link for resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    force: yes

- name: Enable/restart systemd-resolved unit
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes
    enabled: yes
