---
- name: Generate kea-dhcp4.conf configuration file
  template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable/start kea-dhcp4-server unit
  systemd:
    name: kea-dhcp4-server
    state: restarted
    daemon_reload: yes
    enabled: yes
