---
- name: Upgrade packages
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
  - python-systemd
  - nftables
  - keepalived
  - unbound
  - busybox
