---

- name: Generate kubelet.service
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate kubelet default file
  template:
    src: kubelet.j2
    dest: /etc/default/kubelet
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate kubeadm.yaml
  template:
    src: kubeadm.yaml.j2
    dest: /root/kubeadm.yaml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, start/restart kubelet unit
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
