---
- name: Enable sysctl options
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ linux.sysctl.1 }}"

- name: Create a symbolic link for sysctl.conf
  file:
    src: /etc/sysctl.conf
    dest: /etc/sysctl.d/sysctl.conf
    owner: root
    group: root
    state: link
