---
- name: Override /etc/keepalived with an empty directory
  file:
    path: /etc/keepalived
    state: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
  - absent
  - directory

- name: Generate keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, start/restart keepalived unit
  systemd:
    name: keepalived
    state: restarted
    daemon_reload: yes
    enabled: yes
