---
- name: Generate keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Generate bonder.bash
  template:
    src: bonder.bash.j2
    dest: /etc/keepalived/bonder.bash
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Enable, start/restart keepalived unit
  systemd:
    name: keepalived
    state: restarted
    daemon_reload: yes
    enabled: yes
