---
- name: Generate nftables.conf file
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable/restart nftables unit
  systemd:
    name: nftables
    state: restarted
    daemon_reload: yes
    enabled: yes
