---
- name: Load linux modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ linux.modules }}"

- name: Generate /etc/modules-load.conf file
  template:
    src: modules-load.conf.j2
    dest: /etc/modules-load.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Create a symbolic link for modules-load.conf
  file:
    src: /etc/modules-load.conf
    dest: /etc/modules-load.d/modules-load.conf
    owner: root
    group: root
    state: link
