---
- name: Generate dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Disable, stop isc-dhcpd units
  systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: yes
    enabled: no
  loop:
  - isc-dhcp-server
  - isc-dhcp-server6

- name: Create /var/lib/dhcp.brick directory
  file:
    path: /var/lib/dhcp.brick
    state: directory
    owner: dhcpd
    group: dhcpd
    mode: u=rwx,g=rx,o=rx

- name: Create, start volume for DHCP
  gluster_volume:
    state: "{{ item }}"
    name: dhcp
    bricks: /var/lib/dhcp.brick
    force: true
    replicas: "{{ groups[\"skynet\"] | length }}"
    cluster: "[{% for member in groups[\"skynet\"] %}\"{{ hostvars[member][\"networkd\"][\"networks\"][\"skynet\"][\"address\"] }}\"{% if not loop[\"last\"] %},{% endif %}{% endfor %}]"
  run_once: true
  loop:
  - present
  - started

- name: Mount DHCP volume
  mount:
    path: /var/lib/dhcp
    src: "127.0.0.1:/dhcp"
    fstype: glusterfs
    opts: defaults,_netdev
    state: "{{ item }}"
  loop:
  - present
  - mounted
