---
- name: Generate dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, restart isc-dhcpd units
  systemd:
    name: isc-dhcp-server
    state: restarted
    daemon_reload: yes
    enabled: yes
