---
- name: Override /etc/systemd/dnsmasq.service.d with an empty directory
  file:
    path: /etc/systemd/system/dnsmasq.service.d
    state: "{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
  - absent

- name: Generate dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, restart dnsmasq units
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: yes
    enabled: yes
