---
networkd:
  arp_mon: "{% for address in arp_mon.list %}{{ address }} {% endfor %}"
  networks:
    skynet:
      address: 192.168.128.11
      network: "24"
    management:
      address: 192.168.111.11
      network: "24"
