---
interfaces:
- name: onboard
  mac: 90:2b:34:1c:96:2b
  description: Onboard ethernet port
  primary: "true"
- name: extended
  mac: c8:3a:35:d8:e9:53
  description: Extended card ethernet port
  primary: "false"
