---
- name: Generate named.conf
  template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Disable, stop bind unit
  systemd:
    name: bind9
    state: stopped
    daemon_reload: yes
    enabled: no
