---
- name: Generate named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Disable, stop bind unit
  systemd:
    name: bind9
    state: stopped
    daemon_reload: yes
    enabled: no
