---
- name: Create CNI binary directory
  file:
    path: /opt/cni/bin
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Create CNI config directory
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Generate config.toml
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, start/restart containerd unit
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Unarchive crictl
  unarchive:
    src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl.version }}/crictl-{{ crictl.version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes

- name: Generate crictl config file
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
