---
- name: Create CNI binary directory
  file:
    path: /opt/cni/bin
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Unarchive CNI plugins
  unarchive:
    src: "https://github.com/containernetworking/plugins/releases/download/{{ cni.version }}/cni-plugins-linux-amd64-{{ cni.version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes

- name: Create CNI config directory
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Generate CNI configuration
  template:
    src: 10-containerd-net.conflist.j2
    dest: /etc/cni/net.d/10-containerd-net.conflist
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Generate config.toml
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, start/restart containerd unit
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes
