---
- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Generate config.toml
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Enable, start/restart containerd unit
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes
